# fly.toml app configuration file generated for jpostcode-api on 2023-07-23T22:08:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jpostcode-api"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
